In [25]:
import numpy as np

# 行列 A と B の定義
A = np.array([[0, 1], [2, 3], [4, 5]])  # 3×2行列
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])  # 2×4行列

# 行列積を計算し、結果を result に保存
result = np.dot(A, B)

# 行列積の結果を表示
print("行列積の結果:")
print(result)

# 行列積の最大値を取得
max_value = result.max()
print("行列積の結果の最大値:", max_value)


行列積の結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列積の結果の最大値: 47
